# Generated by Django 3.0.5 on 2021-07-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_auto_20210715_1711"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="is_favorited",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="is_in_shopping_cart",
        ),
    ]
