# Generated by Django 3.0.5 on 2021-07-20 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0015_auto_20210720_1946"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_favorite_recipe",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
