# Generated by Django 3.0.5 on 2021-07-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_auto_20210720_2224"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "favorite_recipe"),
                name="unique_favorite_recipe",
            ),
        ),
    ]
